DEBUG = False
TEMPLATE_DEBUG = DEBUG

DATABASE_ENGINE = 'postgresql_psycopg2'
DATABASE_NAME = 'canwest'
DATABASE_USER = 'canwestdbu'
DATABASE_PASSWORD = 'KGTQR41ylV'
DATABASE_HOST = '127.0.0.1'

MEDIA_URL = 'http://canwest-media.taylanpince.com/'

TWITTER_CONSUMER_KEY = 'SgLHvjCwTpOHATcVJSeEKA'
TWITTER_CONSUMER_SECRET = 'goHOe7HRSdLGTH8a8y6xJxd4DKwV8Xs6DYn2gWzRc'
