DEBUG = False
TEMPLATE_DEBUG = DEBUG

DATABASE_ENGINE = 'postgresql_psycopg2'
DATABASE_NAME = 'canwest'
DATABASE_USER = 'canwestdbu'
DATABASE_PASSWORD = 'KGTQR41ylV'
DATABASE_HOST = '127.0.0.1'

MEDIA_URL = 'http://canwest-media.taylanpince.com/'

TWITTER_CONSUMER_KEY = 'Qi0PXu0ZBrSwYv2ERDb45g'
TWITTER_CONSUMER_SECRET = 'RZrqynBZwhewuhpZx3nkTvAKnawjTBYMVNPI73BdHU'
